#%RAML 1.0 NamedExample
value:
-

 
  "userId": "00uooowzckuyZi1GN4x6"
  "source_location": "Bath"
  "destination_location": "london"
  "from_time": "10:30:00"
  "to_time": "11:00:00"
  "Advance_notify_time_min": "30:00:00"
 
-
  
  
  "userId": "00uopf1s08HtHApsn4x6"
  "source_location": "Bath"
  "destination_location": "Bristol"
  "from_time": "6:00:00"
  "to_time": "7:00:00"
  "Advance_notify_time_min": "30:00"
 